ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /code/arduino/Arduino-Makefile
AVRDUDE = /usr/bin/avrdude
BOARDS_TXT = /usr/share/arduino/hardware/arduino/avr/boards.txt
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/avr/cores/arduino
ARDUINO_VAR_PATH  = /usr/share/arduino/hardware/arduino/avr/variants
BOARD_TAG = mini
MCU = atmega328p
#F_CPU = 16000000
AVRDUDE_ISP_BAUDRATE = 19200
#ISP_LOW_FUSE  = 0x62 # avr default
#ISP_LOW_FUSE  = 0xe2
#ISP_HIGH_FUSE = 0xd9 # avr default
ISP_PROG   = stk500v1
#AVRDUDE_ARD_PROGRAMMER = 
#AVRDUDE_ARD_BAUDRATE = 19200
ISP_PORT = /dev/ttyACM1
AVRDUDE_OPTS = -v
#USER_LIB_PATH = ../../src
#ARDUINO_LIBS = JTAG
ARDUINO_HEADER = Arduino.h
OVERRIDE_EXECUTABLES = 1
CC      = $(CC_NAME)
CXX     = $(CXX_NAME)
AS      = $(AS_NAME)
OBJCOPY = $(OBJCOPY_NAME)
OBJDUMP = $(OBJDUMP_NAME)
AR      = $(AR_NAME)
SIZE    = $(SIZE_NAME)
NM      = $(NM_NAME)
ARDUINO_VERSION = $(shell arduino --version 2>/dev/null| cut -d " " -f2 |tr -d '.' )
include /code/arduino/Arduino-Makefile/Arduino.mk
